name: Keep workflows enabled
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git checkout -b keep-alive
      - uses: gautamkrishnar/keepalive-workflow@v1
