name: CI
on: [push, pull_request, workflow_dispatch]
jobs:
  awesome-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: ''
      - run: npx awesome-lint
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        with:
          show-progress: ''
      - name: Lint
        uses: DavidAnson/markdownlint-cli2-action@v5
        with:
          globs: '**/*.md'
